# Generated by Django 5.2.4 on 2025-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soniHouseAgent', '0004_house_is_deleted_landlord_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
